services:
#  redis:
#    image: "redis:alpine"
#    ports:
#      - "6379:6379"
#    #    networks:
#    #     - streamerson
#    network_mode: host
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
networks:
  streamerson:
    name: streamerson
